
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app              # コードをマウント
      - /app/node_modules   # コンテナ内のnode_modulesを保護（上書きされないように）
    command: npm run dev
