services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    image: traiforce-nuxt:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
