name: Deploy to Lightsail

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add Lightsail host key
        run: |
          mkdir -p "$HOME/.ssh"
          ssh-keyscan -H ${{ secrets.LS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.LS_IP }}
          username: ${{ secrets.LS_SSH_USER }}
          key:      ${{ secrets.LS_SSH_KEY }}
          port:     22
          script: |
            echo "=== Deploy start ==="
            cd ~/traiforce
            git pull origin master
            docker compose pull
            docker compose up -d --build
            docker compose logs --tail 50
            echo "=== Deploy done ==="