name: Deploy to Lightsail

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH known host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.LS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LS_IP }}
          username: ${{ secrets.LS_SSH_USER }}
          key: ${{ secrets.LS_SSH_KEY }}
          # key に秘密鍵のテキストを直接渡す形式のため key_path は不要
          script: |
            echo "=== Starting deploy on Lightsail ==="
            cd ~/traiforce
            docker compose pull
            docker compose up -d --build
            docker compose logs -f --tail 50
