# .github/workflows/deploy.yml
name: Deploy to Lightsail2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Lightsail のホスト鍵を known_hosts に追加
      - name: Add Lightsail host key
        run: |
          mkdir -p "$HOME/.ssh"
          ssh-keyscan -H ${{ secrets.LS_IP }} >> "$HOME/.ssh/known_hosts"

      # 3) SSH でリモートデプロイ
      - name: Deploy via SSH
        uses: appleboy/scp-action@v1      # ← ここだけで鍵を扱う
        with:
          host:     ${{ secrets.LS_IP }}
          username: ${{ secrets.LS_SSH_USER }}
          key:      ${{ secrets.LS_SSH_KEY }}
          port:     22
          script: |
            echo "=== Deploy start ==="
            cd ~/traiforce
            git pull origin master
            docker compose pull
            docker compose up -d --build
            echo "=== Last 50 log lines ==="
            docker compose logs --tail 50
            echo "=== Deploy done ==="
