name: Deploy to Lightsail

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3       # リポジトリをクローンするステップ:contentReference[oaicite:5]{index=5}
        with:
          fetch-depth: 0                # フル履歴を取得

      # 2. SSH エージェントをセットアップ
      - name: Setup SSH agent
        uses: webfactory/[email protected]  # 秘密鍵をメモリ上にロード:contentReference[oaicite:6]{index=6}

      # 3. ホスト鍵を known_hosts に追加
      - name: Add Lightsail to known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H ${{ secrets.LS_IP }} >> $HOME/.ssh/known_hosts  # ホスト鍵検証をスキップしない:contentReference[oaicite:7]{index=7}

      # 4. SSH 経由でデプロイ実行
      - name: Deploy via SSH
        uses: appleboy/[email protected]  # リモートコマンド実行アクション:contentReference[oaicite:8]{index=8}
        with:
          host: ${{ secrets.LS_IP }}        # Lightsail の静的 IP
          username: ${{ secrets.LS_SSH_USER }}  # SSH ユーザー名
          key: ${{ secrets.LS_SSH_KEY }}        # 秘密鍵（エージェント経由で提供）
          port: 22
          script: |
            echo "=== Starting deploy on Lightsail ==="
            cd ~/traiforce
            git pull origin master
            docker compose pull
            docker compose up -d --build
            echo "=== Last 50 log lines ==="
            docker compose logs --tail 50
